# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/infra.oneinfra.ereslibre.es_hypervisors.yaml
- bases/cluster.oneinfra.ereslibre.es_components.yaml
- bases/cluster.oneinfra.ereslibre.es_clusters.yaml
- bases/etcd.oneinfra.ereslibre.es_etcdclusters.yaml
- bases/etcd.oneinfra.ereslibre.es_etcdmembers.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
- patches/webhook_in_hypervisors.yaml
- patches/webhook_in_components.yaml
- patches/webhook_in_clusters.yaml
- patches/webhook_in_etcdclusters.yaml
- patches/webhook_in_etcdmembers.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch
- patches/cainjection_in_hypervisors.yaml
- patches/cainjection_in_components.yaml
- patches/cainjection_in_clusters.yaml
- patches/cainjection_in_etcdclusters.yaml
- patches/cainjection_in_etcdmembers.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
